apply plugin: 'scala'

sourceSets {
  main {
    scala.srcDirs = ['src/main/scala', 'src/main/java']
    java.srcDirs = []
  }
}

ext {
  sparkVersion = '3.3.1'
  sparkMajorVersion = '3.3'
  scalaVersion = System.getProperty("scalaVersion") != null ?
          System.getProperty("scalaVersion") : System.getProperty("defaultScalaVersion")
}

dependencies {
  implementation project(path: ':iceberg-bundled-guava', configuration: 'shadow')
  api project(':iceberg-core')
  api project(':iceberg-common')
  api project(':iceberg-data')
  implementation(project(":iceberg-spark:iceberg-spark-${sparkMajorVersion}_${scalaVersion}")) {
    exclude module: 'iceberg-arrow'
  }
  api project(':iceberg-aws')
  api project(':bdp-view')
  implementation libs.caffeine
  implementation "com.netflix.nflxe2etokens:nflx-e2etokens-common:0.13.0"
  api("netflix:metatron-ipc-common:1.307.6") { dep ->
    because "${project.name} sets ${dep.name} version to ${dep.version} explicitly"
  }
  implementation libs.metacat.netflix.client

  implementation(libs.s3authsigncde.s3.auth.sign.client) {
    exclude group: 'com.amazonaws'
    exclude group: 'com.netflix.archaius'
    exclude group: 'netflix'
    exclude group: 'software.amazon.awssdk'
  }
  implementation(libs.s3authsigncde.s3.auth.sts.client) {
    exclude group: 'com.amazonaws'
    exclude group: 'com.netflix.archaius'
    exclude group: 'netflix'
    exclude group: 'software.amazon.awssdk'
  }
  implementation(libs.s3authsigncde.s3.auth.sign.common) {
    exclude group: 'com.amazonaws'
    exclude group: 'com.netflix.archaius'
    exclude group: 'netflix'
    exclude group: 'software.amazon.awssdk'
  }

  implementation libs.bdp.iceberg.acl.storage
  implementation libs.bdp.gandalf
  implementation libs.ksgateway.producer
  implementation libs.dse.metric

  implementation platform(libs.awssdk.bom)
  implementation 'software.amazon.awssdk:regions'
  implementation 'software.amazon.awssdk:s3'
  implementation 'software.amazon.awssdk:sts'
  implementation 'software.amazon.awssdk:url-connection-client'
  implementation 'software.amazon.awssdk:apache-client'

  compileOnly libs.avro.avro
  implementation libs.netflix.spectator.ext.ipc
  compileOnly("org.apache.spark:spark-avro_${scalaVersion}:${sparkVersion}") {
    exclude group: 'org.apache.avro', module: 'avro'
  }
  compileOnly("org.apache.spark:spark-hive_${scalaVersion}:${sparkVersion}") {
    exclude group: 'org.apache.avro', module: 'avro'
    exclude group: 'com.netflix.iceberg'
    exclude group: 'org.apache.iceberg'
  }
  // Override Spark transitive version
  compileOnly "com.netflix.bdp.s3:s3committer:0.12.5"
  compileOnly libs.aws.java.sdk.core
  compileOnly libs.aws.java.sdk.s3
  compileOnly "${libs.bdp.s3fs.get().module}:${libs.bdp.s3fs.get().version}:shadow"

  compileOnly(libs.hadoop2.client) {
    exclude group: 'org.apache.avro', module: 'avro'
    exclude group: 'org.slf4j', module: 'slf4j-log4j12'
  }
  compileOnly project(":iceberg-spark:iceberg-spark-extensions-${sparkMajorVersion}_${scalaVersion}")
  testImplementation project(path: ':iceberg-core', configuration: 'testArtifacts')
  testImplementation(project(":iceberg-spark:iceberg-spark-${sparkMajorVersion}_${scalaVersion}")) {
    exclude module: 'iceberg-arrow'
  }
  testImplementation project(path: ':iceberg-hive-metastore')
  testImplementation project(path: ':iceberg-hive-metastore', configuration: 'testArtifacts')
  testImplementation(libs.mockito.junit.jupiter)
  testImplementation(libs.mockito.core)
  testImplementation(libs.mockito.inline)
}
