
// add enabled Spark version modules to the build the BDP Iceberg Spark Uber Jar for the specified Spark versions
def sparkVersions = (System.getProperty("sparkVersions") != null ? System.getProperty("sparkVersions") : System.getProperty("defaultSparkVersions")).split(",")

if (sparkVersions.contains("3.3")) {
  apply from: file("$projectDir/v3.3/build.gradle")
}

if (sparkVersions.contains("3.5")) {
  apply from: file("$projectDir/v3.5/build.gradle")
}
