apply plugin: 'netflix.lombok'
apply plugin: 'netflix.spotbugs-ci'

spotbugs {
  excludeFilter = file("spotbugs-exclude.xml")
}

dependencies {
  implementation project(path: ':iceberg-bundled-guava', configuration: 'shadow')
  implementation project(':iceberg-core')
  implementation "com.fasterxml.jackson.core:jackson-databind"

  compileOnly('org.apache.hadoop:hadoop-client') {
    exclude group: 'org.apache.avro', module: 'avro'
    exclude group: 'org.slf4j', module: 'slf4j-log4j12'
  }

  testImplementation 'com.google.code.findbugs:annotations:3.0.1'
}
